// Code generated by upd-stubs. DO NOT EDIT.
package echo

import (
	"net/http"
	gen "openapi-mock/internal/generated/echo"
)

type CompositeHandlers struct {
	echo   *EchoHandlers
	status *StatusHandlers
}

func NewCompositeHandlers(echo *EchoHandlers, status *StatusHandlers) gen.ServerInterface {
	return &CompositeHandlers{echo: echo, status: status}
}

var _ gen.ServerInterface = (*CompositeHandlers)(nil)

func (c *CompositeHandlers) Echo(w http.ResponseWriter, r *http.Request) {
	c.echo.Echo(w, r)
}

func (c *CompositeHandlers) EchoHeaders(w http.ResponseWriter, r *http.Request) {
	c.echo.EchoHeaders(w, r)
}

func (c *CompositeHandlers) EchoPath(w http.ResponseWriter, r *http.Request, message string) {
	c.echo.EchoPath(w, r, message)
}

func (c *CompositeHandlers) GetStatus(w http.ResponseWriter, r *http.Request) {
	c.status.GetStatus(w, r)
}
