// Code generated by upd-stubs. DO NOT EDIT.
package echo

import (
	gen "openapi-mock/internal/generated/echo"

	"github.com/labstack/echo/v4"
)

type CompositeHandlers struct {
	echo   *EchoHandlers
	status *StatusHandlers
}

func NewCompositeHandlers(echo *EchoHandlers, status *StatusHandlers) gen.ServerInterface {
	return &CompositeHandlers{echo: echo, status: status}
}

var _ gen.ServerInterface = (*CompositeHandlers)(nil)

func (c *CompositeHandlers) Echo(ctx echo.Context) error {
	return c.echo.Echo(ctx)
}

func (c *CompositeHandlers) EchoHeaders(ctx echo.Context) error {
	return c.echo.EchoHeaders(ctx)
}

func (c *CompositeHandlers) EchoPath(ctx echo.Context, message string) error {
	return c.echo.EchoPath(ctx, message)
}

func (c *CompositeHandlers) GetStatus(ctx echo.Context) error {
	return c.status.GetStatus(ctx)
}
