global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'grpc-mock'
    static_configs:
      - targets: ['grpc-mock:9100']
    metrics_path: '/metrics'
    scrape_interval: 5s
