package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"

	goimports "golang.org/x/tools/imports"
)

// generateOpenAPIProvider generates the provider.go file that implements StrictServerInterface
func generateOpenAPIProvider(outDir string, spec *openapiSpec) error {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by upd-stubs. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", spec.PkgName)
	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t\"context\"\n")
	fmt.Fprintf(&buf, "\tgen %q\n", spec.GenPkgPath)
	fmt.Fprintf(&buf, ")\n\n")

	// Composite struct
	fmt.Fprintf(&buf, "type CompositeHandlers struct {\n")
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		structName := getHandlerStructName(tag)
		fmt.Fprintf(&buf, "\t%s *%s\n", fieldName, structName)
	}
	fmt.Fprintf(&buf, "}\n\n")

	// Constructor
	fmt.Fprintf(&buf, "func NewCompositeHandlers(")
	var params []string
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		structName := getHandlerStructName(tag)
		params = append(params, fmt.Sprintf("%s *%s", fieldName, structName))
	}
	fmt.Fprintf(&buf, "%s) gen.StrictServerInterface {\n", strings.Join(params, ", "))
	fmt.Fprintf(&buf, "\treturn &CompositeHandlers{")
	var assigns []string
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		assigns = append(assigns, fmt.Sprintf("%s: %s", fieldName, fieldName))
	}
	fmt.Fprintf(&buf, "%s}\n", strings.Join(assigns, ", "))
	fmt.Fprintf(&buf, "}\n\n")

	// Interface compliance check
	fmt.Fprintf(&buf, "var _ gen.StrictServerInterface = (*CompositeHandlers)(nil)\n\n")

	// Delegation methods
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		ops := spec.Tags[tag]

		for _, op := range ops {
			methodName := getOperationMethodName(op)

			// Strict signature: (context.Context, gen.<Op>RequestObject) (gen.<Op>ResponseObject, error)
			reqType := fmt.Sprintf("gen.%sRequestObject", methodName)
			respType := fmt.Sprintf("gen.%sResponseObject", methodName)

			fmt.Fprintf(&buf, "func (c *CompositeHandlers) %s(ctx context.Context, request %s) (%s, error) {\n", methodName, reqType, respType)
			fmt.Fprintf(&buf, "\treturn c.%s.%s(ctx, request)\n", fieldName, methodName)
			fmt.Fprintf(&buf, "}\n\n")
		}
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("failed to format provider.go: %v\nSource:\n%s", err, buf.String())
		return err
	}

	src, err = goimports.Process("provider.go", src, nil)
	if err != nil {
		return err
	}

	outPath := filepath.Join(outDir, "provider.go")
	return os.WriteFile(outPath, src, 0o644)
}

func sanitizeFieldName(tag string) string {
	// Handle reserved words
	name := toSnakeCase(tag)
	if name == "default" {
		return "default_"
	}
	return name
}
