package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// generateOpenAPIProvider generates the provider.go file that implements ServerInterface
func generateOpenAPIProvider(outDir string, spec *openapiSpec) error {
	var buf bytes.Buffer

	imports := map[string]string{
		spec.GenPkgPath:               "gen",
		"github.com/labstack/echo/v4": "",
	}

	fmt.Fprintf(&buf, "// Code generated by upd-stubs. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", spec.PkgName)
	writeImports(&buf, imports)
	buf.WriteString("\n")

	// Composite struct
	fmt.Fprintf(&buf, "type CompositeHandlers struct {\n")
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		structName := getHandlerStructName(tag)
		fmt.Fprintf(&buf, "\t%s *%s\n", fieldName, structName)
	}
	fmt.Fprintf(&buf, "}\n\n")

	// Constructor
	fmt.Fprintf(&buf, "func NewCompositeHandlers(")
	var params []string
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		structName := getHandlerStructName(tag)
		params = append(params, fmt.Sprintf("%s *%s", fieldName, structName))
	}
	fmt.Fprintf(&buf, "%s) gen.ServerInterface {\n", strings.Join(params, ", "))
	fmt.Fprintf(&buf, "\treturn &CompositeHandlers{")
	var assigns []string
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		assigns = append(assigns, fmt.Sprintf("%s: %s", fieldName, fieldName))
	}
	fmt.Fprintf(&buf, "%s}\n", strings.Join(assigns, ", "))
	fmt.Fprintf(&buf, "}\n\n")

	// Interface compliance check
	fmt.Fprintf(&buf, "var _ gen.ServerInterface = (*CompositeHandlers)(nil)\n\n")

	// Delegation methods
	for _, tag := range spec.getSortedTags() {
		fieldName := sanitizeFieldName(tag)
		ops := spec.Tags[tag]

		for _, op := range ops {
			methodName := op.OperationID
			if methodName == "" {
				methodName = toPascalCase(op.Method + "_" + strings.ReplaceAll(op.Path, "/", "_"))
			}

			sig := getOpenAPIMethodSignature(spec, op, methodName)

			fmt.Fprintf(&buf, "func (c *CompositeHandlers) %s(%s) %s{\n", methodName, sig.Params, sig.Return)
			fmt.Fprintf(&buf, "\treturn c.%s.%s(%s)\n", fieldName, methodName, sig.ArgList)
			fmt.Fprintf(&buf, "}\n\n")
		}
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("failed to format provider.go: %v\nSource:\n%s", err, buf.String())
		return err
	}

	outPath := filepath.Join(outDir, "provider.go")
	return os.WriteFile(outPath, src, 0o644)
}

func sanitizeFieldName(tag string) string {
	// Handle reserved words
	name := toSnakeCase(tag)
	if name == "default" {
		return "default_"
	}
	return name
}

func extractArgNames(params string) string {
	if params == "" {
		return ""
	}

	parts := strings.Split(params, ",")
	var names []string
	for _, part := range parts {
		part = strings.TrimSpace(part)
		fields := strings.Fields(part)
		if len(fields) >= 1 {
			names = append(names, fields[0])
		}
	}
	return strings.Join(names, ", ")
}
