// Code generated by upd-stubs. DO NOT EDIT.
package petstore

import (
	"net/http"
	gen "openapi-mock/internal/generated/petstore"
)

type CompositeHandlers struct {
	default_ *DefaultHandlers
	pets     *PetsHandlers
}

func NewCompositeHandlers(default_ *DefaultHandlers, pets *PetsHandlers) gen.ServerInterface {
	return &CompositeHandlers{default_: default_, pets: pets}
}

var _ gen.ServerInterface = (*CompositeHandlers)(nil)

func (c *CompositeHandlers) HealthCheck(w http.ResponseWriter, r *http.Request) {
	c.default_.HealthCheck(w, r)
}

func (c *CompositeHandlers) ListPets(w http.ResponseWriter, r *http.Request, params gen.ListPetsParams) {
	c.pets.ListPets(w, r, params)
}

func (c *CompositeHandlers) CreatePet(w http.ResponseWriter, r *http.Request) {
	c.pets.CreatePet(w, r)
}

func (c *CompositeHandlers) DeletePet(w http.ResponseWriter, r *http.Request, petId int64) {
	c.pets.DeletePet(w, r, petId)
}

func (c *CompositeHandlers) GetPetById(w http.ResponseWriter, r *http.Request, petId int64) {
	c.pets.GetPetById(w, r, petId)
}
