// Code generated by upd-stubs. DO NOT EDIT.
package petstore

import (
	"github.com/labstack/echo/v4"
	gen "openapi-mock/internal/generated/petstore"
)

type CompositeHandlers struct {
	default_ *DefaultHandlers
	pets     *PetsHandlers
}

func NewCompositeHandlers(default_ *DefaultHandlers, pets *PetsHandlers) gen.ServerInterface {
	return &CompositeHandlers{default_: default_, pets: pets}
}

var _ gen.ServerInterface = (*CompositeHandlers)(nil)

func (c *CompositeHandlers) HealthCheck(ctx echo.Context) error {
	return c.default_.HealthCheck(ctx)
}

func (c *CompositeHandlers) ListPets(ctx echo.Context, params gen.ListPetsParams) error {
	return c.pets.ListPets(ctx, params)
}

func (c *CompositeHandlers) CreatePet(ctx echo.Context) error {
	return c.pets.CreatePet(ctx)
}

func (c *CompositeHandlers) DeletePet(ctx echo.Context, petId int64) error {
	return c.pets.DeletePet(ctx, petId)
}

func (c *CompositeHandlers) GetPetById(ctx echo.Context, petId int64) error {
	return c.pets.GetPetById(ctx, petId)
}
