// Code generated by upd-stubs. DO NOT EDIT.
package petstore

import (
	"context"
	gen "openapi-mock/internal/generated/petstore"
)

type CompositeHandlers struct {
	default_ *DefaultHandlers
	pets     *PetsHandlers
}

func NewCompositeHandlers(default_ *DefaultHandlers, pets *PetsHandlers) gen.StrictServerInterface {
	return &CompositeHandlers{default_: default_, pets: pets}
}

var _ gen.StrictServerInterface = (*CompositeHandlers)(nil)

func (c *CompositeHandlers) HealthCheck(ctx context.Context, request gen.HealthCheckRequestObject) (gen.HealthCheckResponseObject, error) {
	return c.default_.HealthCheck(ctx, request)
}

func (c *CompositeHandlers) ListPets(ctx context.Context, request gen.ListPetsRequestObject) (gen.ListPetsResponseObject, error) {
	return c.pets.ListPets(ctx, request)
}

func (c *CompositeHandlers) CreatePet(ctx context.Context, request gen.CreatePetRequestObject) (gen.CreatePetResponseObject, error) {
	return c.pets.CreatePet(ctx, request)
}

func (c *CompositeHandlers) DeletePet(ctx context.Context, request gen.DeletePetRequestObject) (gen.DeletePetResponseObject, error) {
	return c.pets.DeletePet(ctx, request)
}

func (c *CompositeHandlers) GetPetById(ctx context.Context, request gen.GetPetByIdRequestObject) (gen.GetPetByIdResponseObject, error) {
	return c.pets.GetPetById(ctx, request)
}
