apiVersion: 1

datasources:
  - name: HTTP Mock Metrics
    type: prometheus
    access: proxy
    # URL will be set via environment variable PROMETHEUS_URL
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: "5s"
