apiVersion: 1

datasources:
  - name: HTTP Mock Metrics
    type: prometheus
    access: proxy
    # URL will be set via environment variable PROMETHEUS_URL
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: "5s"

  - name: HTTP Mock Traces
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpMethod: GET

  - name: HTTP Mock Logs
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
