// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"net/http"
	echo2 "openapi-mock/internal/generated/echo"
	petstore2 "openapi-mock/internal/generated/petstore"
	"openapi-mock/internal/stubs/echo"
	"openapi-mock/internal/stubs/petstore"
)

// Injectors from openapi_wire.go:

func InitializeHTTPApp(middlewares []func(http.Handler) http.Handler, enableLogging bool) (*HTTPApp, error) {
	echoHandlers := echo.NewEchoHandlers(enableLogging)
	statusHandlers := echo.NewStatusHandlers(enableLogging)
	serverInterface := provideEchoHandlers(echoHandlers, statusHandlers)
	defaultHandlers := petstore.NewDefaultHandlers(enableLogging)
	petsHandlers := petstore.NewPetsHandlers(enableLogging)
	petstoreServerInterface := providePetstoreHandlers(defaultHandlers, petsHandlers)
	mux := provideHTTPRouter(middlewares, serverInterface, petstoreServerInterface)
	httpApp := &HTTPApp{
		Router:          mux,
		EchoEcho:        echoHandlers,
		EchoStatus:      statusHandlers,
		PetstoreDefault: defaultHandlers,
		PetstorePets:    petsHandlers,
	}
	return httpApp, nil
}

// openapi_wire.go:

type HTTPApp struct {
	Router          *chi.Mux
	EchoEcho        *echo.EchoHandlers
	EchoStatus      *echo.StatusHandlers
	PetstoreDefault *petstore.DefaultHandlers
	PetstorePets    *petstore.PetsHandlers
}

func provideEchoHandlers(echo3 *echo.EchoHandlers, status *echo.StatusHandlers) echo2.ServerInterface {
	return echo.NewCompositeHandlers(echo3, status)
}

func providePetstoreHandlers(default_ *petstore.DefaultHandlers, pets *petstore.PetsHandlers) petstore2.ServerInterface {
	return petstore.NewCompositeHandlers(default_, pets)
}

func provideHTTPRouter(middlewares []func(http.Handler) http.Handler, echoHandler echo2.ServerInterface, petstoreHandler petstore2.ServerInterface) *chi.Mux {
	r := chi.NewRouter()
	for _, mw := range middlewares {
		r.Use(mw)
	}
	echo2.HandlerFromMux(echoHandler, r)
	petstore2.HandlerFromMux(petstoreHandler, r)
	return r
}

var HTTPProviderSet = wire.NewSet(echo.NewEchoHandlers, echo.NewStatusHandlers, provideEchoHandlers, petstore.NewDefaultHandlers, petstore.NewPetsHandlers, providePetstoreHandlers,
	provideHTTPRouter, wire.Struct(new(HTTPApp), "*"),
)
