// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"net/http"
	echo2 "openapi-mock/internal/generated/echo"
	petstore2 "openapi-mock/internal/generated/petstore"
	"openapi-mock/internal/stubs/echo"
	"openapi-mock/internal/stubs/petstore"
	"openapi-mock/pkg/metrics"
	"openapi-mock/pkg/middleware"
)

// Injectors from openapi_wire.go:

func InitializeHTTPApp(middlewares []func(http.Handler) http.Handler, m *metrics.Metrics, enableLogging bool) (*HTTPApp, error) {
	echoHandlers := echo.NewEchoHandlers(enableLogging)
	statusHandlers := echo.NewStatusHandlers(enableLogging)
	errHandlers := provideErrorHandlers(m)
	serverInterface := provideEchoHandlers(echoHandlers, statusHandlers, errHandlers)
	defaultHandlers := petstore.NewDefaultHandlers(enableLogging)
	petsHandlers := petstore.NewPetsHandlers(enableLogging)
	petstoreServerInterface := providePetstoreHandlers(defaultHandlers, petsHandlers, errHandlers)
	mux := provideHTTPRouter(middlewares, serverInterface, petstoreServerInterface)
	httpApp := &HTTPApp{
		Router:          mux,
		EchoEcho:        echoHandlers,
		EchoStatus:      statusHandlers,
		PetstoreDefault: defaultHandlers,
		PetstorePets:    petsHandlers,
	}
	return httpApp, nil
}

// openapi_wire.go:

type HTTPApp struct {
	Router          *chi.Mux
	EchoEcho        *echo.EchoHandlers
	EchoStatus      *echo.StatusHandlers
	PetstoreDefault *petstore.DefaultHandlers
	PetstorePets    *petstore.PetsHandlers
}

func provideEchoHandlers(echo3 *echo.EchoHandlers, status *echo.StatusHandlers, errHandlers *middleware.ErrorHandlers) echo2.ServerInterface {
	strict := echo.NewCompositeHandlers(echo3, status)
	return echo2.NewStrictHandlerWithOptions(strict, nil, echo2.StrictHTTPServerOptions{
		RequestErrorHandlerFunc:  errHandlers.RequestErrorHandler,
		ResponseErrorHandlerFunc: errHandlers.ResponseErrorHandler,
	})
}

func providePetstoreHandlers(default_ *petstore.DefaultHandlers, pets *petstore.PetsHandlers, errHandlers *middleware.ErrorHandlers) petstore2.ServerInterface {
	strict := petstore.NewCompositeHandlers(default_, pets)
	return petstore2.NewStrictHandlerWithOptions(strict, nil, petstore2.StrictHTTPServerOptions{
		RequestErrorHandlerFunc:  errHandlers.RequestErrorHandler,
		ResponseErrorHandlerFunc: errHandlers.ResponseErrorHandler,
	})
}

func provideErrorHandlers(m *metrics.Metrics) *middleware.ErrorHandlers {
	return middleware.NewErrorHandlers(m)
}

func provideHTTPRouter(middlewares []func(http.Handler) http.Handler, echoHandler echo2.ServerInterface, petstoreHandler petstore2.ServerInterface) *chi.Mux {
	r := chi.NewRouter()
	for _, mw := range middlewares {
		r.Use(mw)
	}
	echo2.HandlerFromMux(echoHandler, r)
	petstore2.HandlerFromMux(petstoreHandler, r)
	return r
}

var HTTPProviderSet = wire.NewSet(echo.NewEchoHandlers, echo.NewStatusHandlers, provideEchoHandlers, petstore.NewDefaultHandlers, petstore.NewPetsHandlers, providePetstoreHandlers,
	provideErrorHandlers, provideHTTPRouter, wire.Struct(new(HTTPApp), "*"),
)
