// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	echo2 "github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"net/http"
	echo3 "openapi-mock/internal/generated/echo"
	petstore2 "openapi-mock/internal/generated/petstore"
	"openapi-mock/internal/stubs/echo"
	"openapi-mock/internal/stubs/petstore"
)

// Injectors from openapi_wire.go:

func InitializeHTTPApp(middlewares []func(http.Handler) http.Handler, enableLogging bool) (*HTTPApp, error) {
	echoHandlers := echo.NewEchoHandlers(enableLogging)
	statusHandlers := echo.NewStatusHandlers(enableLogging)
	serverInterface := provideEchoHandlers(echoHandlers, statusHandlers)
	defaultHandlers := petstore.NewDefaultHandlers(enableLogging)
	petsHandlers := petstore.NewPetsHandlers(enableLogging)
	petstoreServerInterface := providePetstoreHandlers(defaultHandlers, petsHandlers)
	echoEcho := provideHTTPEcho(middlewares, serverInterface, petstoreServerInterface)
	httpApp := &HTTPApp{
		Echo:            echoEcho,
		EchoEcho:        echoHandlers,
		EchoStatus:      statusHandlers,
		PetstoreDefault: defaultHandlers,
		PetstorePets:    petsHandlers,
	}
	return httpApp, nil
}

// openapi_wire.go:

type HTTPApp struct {
	Echo            *echo2.Echo
	EchoEcho        *echo.EchoHandlers
	EchoStatus      *echo.StatusHandlers
	PetstoreDefault *petstore.DefaultHandlers
	PetstorePets    *petstore.PetsHandlers
}

func provideEchoHandlers(echo4 *echo.EchoHandlers, status *echo.StatusHandlers) echo3.ServerInterface {
	return echo.NewCompositeHandlers(echo4, status)
}

func providePetstoreHandlers(default_ *petstore.DefaultHandlers, pets *petstore.PetsHandlers) petstore2.ServerInterface {
	return petstore.NewCompositeHandlers(default_, pets)
}

func provideHTTPEcho(middlewares []func(http.Handler) http.Handler, echoHandler echo3.ServerInterface, petstoreHandler petstore2.ServerInterface) *echo2.Echo {
	e := echo2.New()
	for _, mwHTTP := range middlewares {
		e.Use(echo2.WrapMiddleware(mwHTTP))
	}
	e.HideBanner = true
	e.Use(middleware.Recover())
	echo3.RegisterHandlers(e, echoHandler)
	petstore2.RegisterHandlers(e, petstoreHandler)
	return e
}

var HTTPProviderSet = wire.NewSet(echo.NewEchoHandlers, echo.NewStatusHandlers, provideEchoHandlers, petstore.NewDefaultHandlers, petstore.NewPetsHandlers, providePetstoreHandlers,
	provideHTTPEcho, wire.Struct(new(HTTPApp), "*"),
)
