openapi: "3.0.0"
info:
  title: Petstore API
  version: "1.0.0"
paths:
  /pets:
    $ref: './paths/pets.yaml#/pets'
  /pets/{petId}:
    $ref: './paths/pets.yaml#/pet_details'
  /health:
    $ref: './paths/system.yaml#/health'
components:
  schemas:
    Pet:
      $ref: './schemas/Pet.yaml'
    NewPet:
      $ref: './schemas/NewPet.yaml'
