// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: complex/service/api.proto

package service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	deprecatedmodels "grpc-mock/internal/genproto/complex/deprecatedmodels"
	importme "grpc-mock/internal/genproto/complex/importme"
	models "grpc-mock/internal/genproto/complex/models"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_complex_service_api_proto protoreflect.FileDescriptor

const file_complex_service_api_proto_rawDesc = "" +
	"\n" +
	"\x19complex/service/api.proto\x12\x0fcomplex.service\x1a\x1ccomplex/service/models.proto\x1a\x1fcomplex/service/oldmodels.proto\x1a\x1bcomplex/importme/data.proto\x1a\x1cgoogle/api/annotations.proto2\xc0\x02\n" +
	"\x0eComplexService\x12Y\n" +
	"\bGetModel\x12\x1c.complex.models.ServiceModel\x1a\x1c.complex.models.ServiceModel\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/model\x12s\n" +
	"\vGetOldModel\x12&.complex.deprecatedmodels.ServiceModel\x1a&.complex.deprecatedmodels.ServiceModel\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/oldmodel\x12^\n" +
	"\tDoNothing\x12\x1b.complex.importme.NothingIn\x1a\x1c.complex.importme.NothingOut\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/nothingB5Z3grpc-mock/internal/genproto/complex/service;serviceb\x06proto3"

var file_complex_service_api_proto_goTypes = []any{
	(*models.ServiceModel)(nil),           // 0: complex.models.ServiceModel
	(*deprecatedmodels.ServiceModel)(nil), // 1: complex.deprecatedmodels.ServiceModel
	(*importme.NothingIn)(nil),            // 2: complex.importme.NothingIn
	(*importme.NothingOut)(nil),           // 3: complex.importme.NothingOut
}
var file_complex_service_api_proto_depIdxs = []int32{
	0, // 0: complex.service.ComplexService.GetModel:input_type -> complex.models.ServiceModel
	1, // 1: complex.service.ComplexService.GetOldModel:input_type -> complex.deprecatedmodels.ServiceModel
	2, // 2: complex.service.ComplexService.DoNothing:input_type -> complex.importme.NothingIn
	0, // 3: complex.service.ComplexService.GetModel:output_type -> complex.models.ServiceModel
	1, // 4: complex.service.ComplexService.GetOldModel:output_type -> complex.deprecatedmodels.ServiceModel
	3, // 5: complex.service.ComplexService.DoNothing:output_type -> complex.importme.NothingOut
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_complex_service_api_proto_init() }
func file_complex_service_api_proto_init() {
	if File_complex_service_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_complex_service_api_proto_rawDesc), len(file_complex_service_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_complex_service_api_proto_goTypes,
		DependencyIndexes: file_complex_service_api_proto_depIdxs,
	}.Build()
	File_complex_service_api_proto = out.File
	file_complex_service_api_proto_goTypes = nil
	file_complex_service_api_proto_depIdxs = nil
}
