// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: complex/service/api.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	deprecatedmodels "grpc-mock/internal/genproto/complex/deprecatedmodels"
	importme "grpc-mock/internal/genproto/complex/importme"
	models "grpc-mock/internal/genproto/complex/models"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComplexService_GetModel_FullMethodName    = "/complex.service.ComplexService/GetModel"
	ComplexService_GetOldModel_FullMethodName = "/complex.service.ComplexService/GetOldModel"
	ComplexService_DoNothing_FullMethodName   = "/complex.service.ComplexService/DoNothing"
)

// ComplexServiceClient is the client API for ComplexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComplexServiceClient interface {
	GetModel(ctx context.Context, in *models.ServiceModel, opts ...grpc.CallOption) (*models.ServiceModel, error)
	GetOldModel(ctx context.Context, in *deprecatedmodels.ServiceModel, opts ...grpc.CallOption) (*deprecatedmodels.ServiceModel, error)
	DoNothing(ctx context.Context, in *importme.NothingIn, opts ...grpc.CallOption) (*importme.NothingOut, error)
}

type complexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComplexServiceClient(cc grpc.ClientConnInterface) ComplexServiceClient {
	return &complexServiceClient{cc}
}

func (c *complexServiceClient) GetModel(ctx context.Context, in *models.ServiceModel, opts ...grpc.CallOption) (*models.ServiceModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.ServiceModel)
	err := c.cc.Invoke(ctx, ComplexService_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complexServiceClient) GetOldModel(ctx context.Context, in *deprecatedmodels.ServiceModel, opts ...grpc.CallOption) (*deprecatedmodels.ServiceModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(deprecatedmodels.ServiceModel)
	err := c.cc.Invoke(ctx, ComplexService_GetOldModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complexServiceClient) DoNothing(ctx context.Context, in *importme.NothingIn, opts ...grpc.CallOption) (*importme.NothingOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(importme.NothingOut)
	err := c.cc.Invoke(ctx, ComplexService_DoNothing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplexServiceServer is the server API for ComplexService service.
// All implementations must embed UnimplementedComplexServiceServer
// for forward compatibility.
type ComplexServiceServer interface {
	GetModel(context.Context, *models.ServiceModel) (*models.ServiceModel, error)
	GetOldModel(context.Context, *deprecatedmodels.ServiceModel) (*deprecatedmodels.ServiceModel, error)
	DoNothing(context.Context, *importme.NothingIn) (*importme.NothingOut, error)
	mustEmbedUnimplementedComplexServiceServer()
}

// UnimplementedComplexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComplexServiceServer struct{}

func (UnimplementedComplexServiceServer) GetModel(context.Context, *models.ServiceModel) (*models.ServiceModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedComplexServiceServer) GetOldModel(context.Context, *deprecatedmodels.ServiceModel) (*deprecatedmodels.ServiceModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOldModel not implemented")
}
func (UnimplementedComplexServiceServer) DoNothing(context.Context, *importme.NothingIn) (*importme.NothingOut, error) {
	return nil, status.Error(codes.Unimplemented, "method DoNothing not implemented")
}
func (UnimplementedComplexServiceServer) mustEmbedUnimplementedComplexServiceServer() {}
func (UnimplementedComplexServiceServer) testEmbeddedByValue()                        {}

// UnsafeComplexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComplexServiceServer will
// result in compilation errors.
type UnsafeComplexServiceServer interface {
	mustEmbedUnimplementedComplexServiceServer()
}

func RegisterComplexServiceServer(s grpc.ServiceRegistrar, srv ComplexServiceServer) {
	// If the following call panics, it indicates UnimplementedComplexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComplexService_ServiceDesc, srv)
}

func _ComplexService_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.ServiceModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplexServiceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplexService_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplexServiceServer).GetModel(ctx, req.(*models.ServiceModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplexService_GetOldModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(deprecatedmodels.ServiceModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplexServiceServer).GetOldModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplexService_GetOldModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplexServiceServer).GetOldModel(ctx, req.(*deprecatedmodels.ServiceModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplexService_DoNothing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(importme.NothingIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplexServiceServer).DoNothing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplexService_DoNothing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplexServiceServer).DoNothing(ctx, req.(*importme.NothingIn))
	}
	return interceptor(ctx, in, info, handler)
}

// ComplexService_ServiceDesc is the grpc.ServiceDesc for ComplexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComplexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "complex.service.ComplexService",
	HandlerType: (*ComplexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModel",
			Handler:    _ComplexService_GetModel_Handler,
		},
		{
			MethodName: "GetOldModel",
			Handler:    _ComplexService_GetOldModel_Handler,
		},
		{
			MethodName: "DoNothing",
			Handler:    _ComplexService_DoNothing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "complex/service/api.proto",
}
