// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: complex/service/models.proto

package models

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	importme "grpc-mock/internal/genproto/complex/importme"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *importme.ImportedData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *date.Date             `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceModel) Reset() {
	*x = ServiceModel{}
	mi := &file_complex_service_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceModel) ProtoMessage() {}

func (x *ServiceModel) ProtoReflect() protoreflect.Message {
	mi := &file_complex_service_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceModel.ProtoReflect.Descriptor instead.
func (*ServiceModel) Descriptor() ([]byte, []int) {
	return file_complex_service_models_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceModel) GetData() *importme.ImportedData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServiceModel) GetCreatedAt() *date.Date {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_complex_service_models_proto protoreflect.FileDescriptor

const file_complex_service_models_proto_rawDesc = "" +
	"\n" +
	"\x1ccomplex/service/models.proto\x12\x0ecomplex.models\x1a\x1bcomplex/importme/data.proto\x1a\x16google/type/date.proto\"t\n" +
	"\fServiceModel\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.complex.importme.ImportedDataR\x04data\x120\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x11.google.type.DateR\tcreatedAtB3Z1grpc-mock/internal/genproto/complex/models;modelsb\x06proto3"

var (
	file_complex_service_models_proto_rawDescOnce sync.Once
	file_complex_service_models_proto_rawDescData []byte
)

func file_complex_service_models_proto_rawDescGZIP() []byte {
	file_complex_service_models_proto_rawDescOnce.Do(func() {
		file_complex_service_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_complex_service_models_proto_rawDesc), len(file_complex_service_models_proto_rawDesc)))
	})
	return file_complex_service_models_proto_rawDescData
}

var file_complex_service_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_complex_service_models_proto_goTypes = []any{
	(*ServiceModel)(nil),          // 0: complex.models.ServiceModel
	(*importme.ImportedData)(nil), // 1: complex.importme.ImportedData
	(*date.Date)(nil),             // 2: google.type.Date
}
var file_complex_service_models_proto_depIdxs = []int32{
	1, // 0: complex.models.ServiceModel.data:type_name -> complex.importme.ImportedData
	2, // 1: complex.models.ServiceModel.created_at:type_name -> google.type.Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_complex_service_models_proto_init() }
func file_complex_service_models_proto_init() {
	if File_complex_service_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_complex_service_models_proto_rawDesc), len(file_complex_service_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_complex_service_models_proto_goTypes,
		DependencyIndexes: file_complex_service_models_proto_depIdxs,
		MessageInfos:      file_complex_service_models_proto_msgTypes,
	}.Build()
	File_complex_service_models_proto = out.File
	file_complex_service_models_proto_goTypes = nil
	file_complex_service_models_proto_depIdxs = nil
}
