// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: complex/importme/data.proto

package importme

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedData) Reset() {
	*x = ImportedData{}
	mi := &file_complex_importme_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedData) ProtoMessage() {}

func (x *ImportedData) ProtoReflect() protoreflect.Message {
	mi := &file_complex_importme_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedData.ProtoReflect.Descriptor instead.
func (*ImportedData) Descriptor() ([]byte, []int) {
	return file_complex_importme_data_proto_rawDescGZIP(), []int{0}
}

func (x *ImportedData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NothingIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NothingIn) Reset() {
	*x = NothingIn{}
	mi := &file_complex_importme_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NothingIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NothingIn) ProtoMessage() {}

func (x *NothingIn) ProtoReflect() protoreflect.Message {
	mi := &file_complex_importme_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NothingIn.ProtoReflect.Descriptor instead.
func (*NothingIn) Descriptor() ([]byte, []int) {
	return file_complex_importme_data_proto_rawDescGZIP(), []int{1}
}

type NothingOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NothingOut) Reset() {
	*x = NothingOut{}
	mi := &file_complex_importme_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NothingOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NothingOut) ProtoMessage() {}

func (x *NothingOut) ProtoReflect() protoreflect.Message {
	mi := &file_complex_importme_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NothingOut.ProtoReflect.Descriptor instead.
func (*NothingOut) Descriptor() ([]byte, []int) {
	return file_complex_importme_data_proto_rawDescGZIP(), []int{2}
}

var File_complex_importme_data_proto protoreflect.FileDescriptor

const file_complex_importme_data_proto_rawDesc = "" +
	"\n" +
	"\x1bcomplex/importme/data.proto\x12\x10complex.importme\"$\n" +
	"\fImportedData\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\v\n" +
	"\tNothingIn\"\f\n" +
	"\n" +
	"NothingOutB7Z5grpc-mock/internal/genproto/complex/importme;importmeb\x06proto3"

var (
	file_complex_importme_data_proto_rawDescOnce sync.Once
	file_complex_importme_data_proto_rawDescData []byte
)

func file_complex_importme_data_proto_rawDescGZIP() []byte {
	file_complex_importme_data_proto_rawDescOnce.Do(func() {
		file_complex_importme_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_complex_importme_data_proto_rawDesc), len(file_complex_importme_data_proto_rawDesc)))
	})
	return file_complex_importme_data_proto_rawDescData
}

var file_complex_importme_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_complex_importme_data_proto_goTypes = []any{
	(*ImportedData)(nil), // 0: complex.importme.ImportedData
	(*NothingIn)(nil),    // 1: complex.importme.NothingIn
	(*NothingOut)(nil),   // 2: complex.importme.NothingOut
}
var file_complex_importme_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_complex_importme_data_proto_init() }
func file_complex_importme_data_proto_init() {
	if File_complex_importme_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_complex_importme_data_proto_rawDesc), len(file_complex_importme_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_complex_importme_data_proto_goTypes,
		DependencyIndexes: file_complex_importme_data_proto_depIdxs,
		MessageInfos:      file_complex_importme_data_proto_msgTypes,
	}.Build()
	File_complex_importme_data_proto = out.File
	file_complex_importme_data_proto_goTypes = nil
	file_complex_importme_data_proto_depIdxs = nil
}
